# Support Vector Machine

## 1. Linear Classification

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

iris = datasets.load_iris()
x = iris['data'][:, (2, 3)]  # petal length, petal width
y = (iris['target'] == 2).astype(np.float64)  # Iris virginica

The C hyperparameter manages *hard/soft margin classification* balance. If C is small, there are more margin violations than in the case when C is high. If an SVM model is overfitting, it is possible to regularize it by reducing C.

In [2]:
svm_clf = Pipeline([
    ('scaler', StandardScaler()),
    ('linear_svc', LinearSVC(C=1, loss='hinge'))
])
svm_clf.fit(x, y)
svm_clf.predict([[5.5, 1.7]])

array([1.])

Instead of using the `LinearSVC` class, we could use the `SVC` class with a linear kernel to get the same but slower model

In [3]:
from sklearn.svm import SVC

svc_clf = Pipeline([
    ('scaler', StandardScaler()),
    ('linear_svc', SVC(kernel='linear', C=1))
])
svc_clf.fit(x, y)
svc_clf.predict([[5.5, 1.7]])

array([1.])

Or the `SGDClassifier`

In [4]:
from sklearn.linear_model import SGDClassifier

sgd_clf = Pipeline([
    ('scaler', StandardScaler()),
    ('linear_sgd', SGDClassifier(loss='hinge', alpha=1/len(x)))
])
sgd_clf.fit(x, y)
sgd_clf.predict([[5.5, 1.7]])

array([1.])

## 2. Nonlinear Classification

In [5]:
from sklearn.datasets import make_moons
from sklearn.preprocessing import PolynomialFeatures

x, y = make_moons(n_samples=100, noise=0.15)
polynomial_svm_clf = Pipeline([
    ('poly_features', PolynomialFeatures(degree=3)),
    ('scaler', StandardScaler()),
    ('svm_clf', LinearSVC(C=10, loss='hinge'))
])

polynomial_svm_clf.fit(x, y)
polynomial_svm_clf.predict([[5.5, 1.7]])

/home/enorkin/learning/kaggle/venv/lib/python3.8/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


array([1])

### Kernel Trick

The *kernel trick* makes it possible to get the same result as if you had added many polynomial features, even with very high-degree polinomials.

In [6]:
poly_kernel_svm_clf = Pipeline([
    ('scaler', StandardScaler()),
    ('svm_clf', SVC(kernel='poly', degree=3, coef0=1, C=5))
])

poly_kernel_svm_clf.fit(x, y)
poly_kernel_svm_clf.predict([[5.5, 1.7]])

array([1])

If the model is overfitting, you might want to reduce polynomial degree. The hyperparameter `coef0` controls how much the model is influenced by high-degree polynomials versus low-degree polymomials. Use `GridSearch` to find the right hyperparameters.

### Gaussian RBF Kernel

In [7]:
rbf_kernel_svm_clf = Pipeline([
    ('scaler', StandardScaler()),
    ('svm_clf', SVC(kernel='rbf', gamma=5, C=1e-3))
])

rbf_kernel_svm_clf.fit(x, y)
rbf_kernel_svm_clf.predict([[5.5, 1.7]])

array([1])